=== sunwaysoftware/Interface/431000/source/XML&JSON/BDC_Response.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="INFO">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="RESULT_FLAG" type="xs:integer" default="1"></xs:element>
                <xs:element name="RESULT_MESSAGE" type="xs:string" default="查询成功!"></xs:element>
                <xs:element name="QLR" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="FSQRMC" type="xs:string"/>
                            <xs:element name="FZJHM" type="xs:string"/>   
                            <xs:element name="FDCQINFO">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="FDCQ" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="CQZH" type="xs:string"></xs:element>
                                                    <xs:element name="FBDCDYH" type="xs:string"></xs:element>
                                                    <xs:element name="FFDZL" type="xs:string"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sunwaysoftware/Interface/431000/source/XML&JSON/instance_Response1.xml
<?xml version="1.0" encoding="UTF-8"?>
<INFO xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/GitHub/Interface/431000/source/XML%26JSON/BDC_Response.xsd">
    <RESULT_FLAG>1</RESULT_FLAG>
    <RESULT_MESSAGE>查询成功!</RESULT_MESSAGE>
    <QLR>
        <FSQRMC>FSQRMC0</FSQRMC>
        <FZJHM>FZJHM0</FZJHM>
        <FDCQINFO>
            <FDCQ>
                <CQZH>CQZH0</CQZH>
                <FBDCDYH>FBDCDYH0</FBDCDYH>
                <FFDZL>FFDZL0</FFDZL>
            </FDCQ>
            <FDCQ>
                <CQZH>CQZH1</CQZH>
                <FBDCDYH>FBDCDYH1</FBDCDYH>
                <FFDZL>FFDZL1</FFDZL>
            </FDCQ>
        </FDCQINFO>
    </QLR>
    <QLR>
        <FSQRMC>FSQRMC1</FSQRMC>
        <FZJHM>FZJHM1</FZJHM>
        <FDCQINFO>
            <FDCQ>
                <CQZH>CQZH2</CQZH>
                <FBDCDYH>FBDCDYH2</FBDCDYH>
                <FFDZL>FFDZL2</FFDZL>
            </FDCQ>
            <FDCQ>
                <CQZH>CQZH3</CQZH>
                <FBDCDYH>FBDCDYH3</FBDCDYH>
                <FFDZL>FFDZL3</FFDZL>
            </FDCQ>
        </FDCQINFO>
    </QLR>
</INFO>
